CREATE TABLE CLIENTES(
USUARIO VARCHAR(20),
PASS VARCHAR(20),
NOMBRE VARCHAR(20),
EMAIL VARCHAR(50),
ID	int(10) not null auto_increment,
PRIMARY KEY (ID)
);
CREATE TABLE CUENTAS(
NUM_CUENTA INT(10) not null auto_increment,
IDCLIENTE INT(10) NOT NULL,
ALIAS VARCHAR(20),
SALDO float(20),
PRIMARY KEY (NUM_CUENTA),
FOREIGN KEY (IDCLIENTE) REFERENCES CLIENTES (ID)
);
CREATE TABLE TIPOS_MOVIMIENTO(
ID INT(10) NOT NULL auto_increment,
TIPO VARCHAR(15),
PRIMARY KEY (ID)
);
CREATE TABLE MOVIMIENTOS(
ID INT(10) NOT NULL auto_increment,
IDMOVIMIENTO INT(10),
DESCRIPCION VARCHAR(20),
FECHA DATE,
IMPORTE INT(20),
NUMEROCUENTA INT(10),
PRIMARY KEY (ID),
FOREIGN KEY (NUMEROCUENTA) REFERENCES CUENTAS (NUM_CUENTA),
FOREIGN KEY (IDMOVIMIENTO) REFERENCES TIPOS_MOVIMIENTO (ID)
);
CREATE TABLE PRESTAMOS(
ID INT(10) NOT NULL auto_increment,
DESCRIPCION VARCHAR(20),
FECHA DATE,
IMPORTE INT(20),
PLAZOS INT(100),
NUMEROCUENTA INT(10),
PRIMARY KEY (ID),
FOREIGN KEY (NUMEROCUENTA) REFERENCES CUENTAS (NUM_CUENTA)
);
CREATE TABLE AMORTIZACIONES(
ID INT(10) NOT NULL auto_increment,
FECHA DATE,
IMPORTE INT(10),
IDPRESTAMO INT(10),
PRIMARY KEY (ID),
FOREIGN KEY (IDPRESTAMO) REFERENCES PRESTAMOS (ID)
)